dataset:
  name: clutter
  data_dir: data/mops_data/mops-kitchen-5k
  num_classes: 56
  labels: [affordance]

model:
  name: dinov3_segmentation
  model_name: facebook/dinov3-vitb16-pretrain-lvd1689m
  num_classes: 56
  task: affordance
  multilabel: true
  freeze_backbone: true
  lr: 0.001
  hidden_dim: 256

training:
  batch_size: 16
  num_epochs: 10
